remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter

# site metadata settings
title: David Le Chan
description: A description of your site.
baseurl: "" 
url: "https://davidlechan.dev"
